site_name: Credential Theft Lab
pages:
  - Overview: 'index.md'
  - Getting Started: 'gettingstarted.md'
  - What's Been Done For You: 'priorconfiguration.md'
  - Credential Phishing Prevention: 'credentialphishing.md'
  - Multi-Factor Authentication: 'mfa.md'
theme: readthedocs